runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/google/identity-credential.git#e5dccffa9f56327db8e9b0cffa9c662cdb85e632'
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /request-mdl
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
